language: node_js
addons:
  firefox: "45.0"
node_js:
  - "4"
  - "0.12"
  - "0.11"
before_script:
    - 'export CHROME_BIN=chromium-browser'
    - 'export DISPLAY=:99.0'
    - 'sh -e /etc/init.d/xvfb start'
    - 'npm install'
